package vista;

import entidades.Producto;
import entidades.ProductoCarrito;
import interfaces.IControlador;
import interfaces.IModeloLeible;
import interfaces.Subscriber;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import util.SoloEnterosPositivosFilter;

/**
 *
 * @author janot
 */
public class CantidadProducto extends javax.swing.JDialog implements Subscriber{
    
    private final IModeloLeible modeloLeible;
    private final IControlador controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CantidadProducto.class.getName());

    /**
     * Creates new form CantidadProducto
     */
    public CantidadProducto(java.awt.Frame parent, boolean modal, IModeloLeible modeloLeible, IControlador controlador) {
        super(parent, modal);
        this.modeloLeible = modeloLeible;
        this.controlador = controlador;
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setResizable(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(51, 153, 255));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidad.setText("Cantidad:");
        jPanelPrincipal.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 100, 30));

        jLabelProducto.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabelProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProducto.setText("Producto");
        jPanelPrincipal.add(jLabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 60));
        jPanelPrincipal.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, 30));
        ((AbstractDocument) jTextFieldCantidad.getDocument())
        .setDocumentFilter(new SoloEnterosPositivosFilter());

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controlador.ocultarPantallaCantidadProducto();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseClicked
        controlador.ocultarPantallaCantidadProducto();
    }//GEN-LAST:event_jButtonCancelarMouseClicked

    private void jButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMouseClicked
        agregarProductoAcarrito();
    }//GEN-LAST:event_jButtonAgregarMouseClicked


    private void setLabelProducto(){
        jLabelProducto.setText(modeloLeible.obtenerProductoSeleccionado().getNombre());
    }
    
    private void agregarProductoAcarrito(){
        Producto producto = modeloLeible.obtenerProductoSeleccionado();
        
        if(jTextFieldCantidad.getText() == null || jTextFieldCantidad.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Cantidad no puede estar vacia", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int cantidad = Integer.parseInt(jTextFieldCantidad.getText());
            if(cantidad == 0){
                JOptionPane.showMessageDialog(this, "Cantidad no puede ser igual a 0", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            }
            else{

                ProductoCarrito pC = new ProductoCarrito(producto, cantidad);
                controlador.agregarProductoAlCarrito(pC);
                controlador.ocultarPantallaCantidadProducto();
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        //Validacion para actualizar el producto si es que no es nulo
        if(modeloLeible.obtenerProductoSeleccionado()!= null){
            setLabelProducto();
            jTextFieldCantidad.setText("1");
        }
        
        this.setVisible(modeloLeible.isMostrandoPantallaCantidadProducto());
        
    }
}
