package vista;

import controlador.Controlador;
import entidades.Producto;
import entidades.ProductoCarrito;
import interfaces.IControlador;
import interfaces.IModeloLeible;
import interfaces.Subscriber;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author janot
 */
public class CarritoCompras extends javax.swing.JFrame implements Subscriber{
    private final IModeloLeible modeloLeible;
    private final IControlador controlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CarritoCompras.class.getName());

    /**
     * Creates new form CarritoCompras
     * @param modeloLeible
     */
    public CarritoCompras(IModeloLeible modeloLeible, IControlador controlador) {
        this.modeloLeible = modeloLeible;
        this.controlador = controlador;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProductosCarrito = new javax.swing.JList<>();
        jPanelBtnPagar = new javax.swing.JPanel();
        jLabelPagar = new javax.swing.JLabel();
        jLabelSubtotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();
        jLabelAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/compras (1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Holaaa, Juan Perez!!!");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 420, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListProductosCarrito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jListProductosCarrito.setModel(new javax.swing.AbstractListModel<ProductoCarrito>() {
            ProductoCarrito[] productosCarrito = {};
            public int getSize() { return productosCarrito.length; }
            public ProductoCarrito getElementAt(int i) { return productosCarrito[i]; }
        });
        jScrollPane1.setViewportView(jListProductosCarrito);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 180));

        jPanelBtnPagar.setBackground(new java.awt.Color(51, 153, 255));
        jPanelBtnPagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPagar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelPagar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPagar.setText("Pagar");
        jLabelPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPagarMouseExited(evt);
            }
        });
        jPanelBtnPagar.add(jLabelPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        jPanel3.add(jPanelBtnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 150, 40));

        jLabelSubtotal.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabelSubtotal.setText("Subtotal:");
        jPanel3.add(jLabelSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 320, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Carrito de compras");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        jLabelTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabelTotal.setText("Total (+16%Iva):");
        jPanel3.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 320, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 330, 420));

        jListProductos.setBackground(new java.awt.Color(0, 153, 255));
        jListProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jListProductos.setForeground(new java.awt.Color(255, 255, 255));
        jListProductos.setModel(new javax.swing.AbstractListModel<Producto>() {
            Producto[] productos = { };
            public int getSize() { return productos.length; }
            public Producto getElementAt(int i) { return productos[i]; }
        });
        jListProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListProductos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 430, 370));

        jLabelAviso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAviso.setText("*Doble Click Para seleccionar producto*");
        jPanel1.add(jLabelAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 430, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarMouseEntered
        jPanelBtnPagar.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_jLabelPagarMouseEntered

    private void jLabelPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarMouseExited
        jPanelBtnPagar.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_jLabelPagarMouseExited

    private void jListProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProductosMouseClicked
        accionSeleccionarProducto(evt);
    }//GEN-LAST:event_jListProductosMouseClicked

    private void jLabelPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPagarMouseClicked
        pagar();
    }//GEN-LAST:event_jLabelPagarMouseClicked

    private void accionSeleccionarProducto(java.awt.event.MouseEvent evt){
        if (evt.getClickCount() == 2) {
            Producto seleccionado = jListProductos.getSelectedValue();
            if (seleccionado != null) {
                controlador.seleccionarProducto(seleccionado);
                controlador.mostrarPantallaCantidadProducto();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelPagar;
    private javax.swing.JLabel jLabelSubtotal;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JList<Producto> jListProductos;
    private javax.swing.JList<ProductoCarrito> jListProductosCarrito;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBtnPagar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        this.setVisible(modeloLeible.isMostrandoPantallaCarritoCompras());
        cargarProductos();
        cargarProductosCarrito();
        cargarSubtotal();
        cargarTotal();
    }
    
    private void cargarProductos(){
        jListProductos.setModel(new javax.swing.AbstractListModel<Producto>() {
            List<Producto> productos = modeloLeible.obtenerProductos();
                public int getSize() { return productos.size();}
                public Producto getElementAt(int i) { return productos.get(i); }
        });
    }
    
    private void cargarProductosCarrito(){
        jListProductosCarrito.setModel(new javax.swing.AbstractListModel<ProductoCarrito>() {
            List<ProductoCarrito> productosCarrito = modeloLeible.obtenerProductosDelCarrito();
                public int getSize() { return productosCarrito.size();}
                public ProductoCarrito getElementAt(int i) { return productosCarrito.get(i); }
        });
    }

    private void cargarSubtotal(){
        List<ProductoCarrito> listaProductosCarrito = modeloLeible.obtenerProductosDelCarrito();
        double subtotal = 0.0;
        
        for (ProductoCarrito productoCarrito : listaProductosCarrito) {
            subtotal += productoCarrito.getProducto().getPrecio() * productoCarrito.getCantidad();
        }
        
        double redondeado = Math.round(subtotal * 100.0) / 100.0;
        
        String textoSubtotal = "Subtotal:  $" + redondeado;
        jLabelSubtotal.setText(textoSubtotal);
    }
    
    private void cargarTotal(){
        List<ProductoCarrito> listaProductosCarrito = modeloLeible.obtenerProductosDelCarrito();
        double subtotal = 0.0;
        
        for (ProductoCarrito productoCarrito : listaProductosCarrito) {
            subtotal += productoCarrito.getProducto().getPrecio() * productoCarrito.getCantidad();
        }
        
        double iva = subtotal * 0.16;
        double total = subtotal + iva;
        
        double redondeado = Math.round(total * 100.0) / 100.0;
        
        String textoTotal = "Total (+16%Iva): $" + redondeado;
        jLabelTotal.setText(textoTotal);
    }
    
    private void pagar(){
        if(modeloLeible.obtenerProductosDelCarrito().size() == 0){
            JOptionPane.showMessageDialog(this,"No se pudo realizar compra: Carrito Vacio", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else{
            controlador.realizarCompra();
        }
    }
}
