package vista;

import interfaces.IControlador;
import interfaces.IModeloLeible;
import interfaces.Subscriber;
import java.awt.Color;

/**
 *
 * @author janot
 */
public class StatusPago extends javax.swing.JDialog implements Subscriber{
    IModeloLeible modeloLeible;
    IControlador controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatusPago.class.getName());

    /**
     * Creates new form StatusPago
     */
    public StatusPago(java.awt.Frame parent, boolean modal, IModeloLeible modeloLeible, IControlador controlador) {
        this.modeloLeible = modeloLeible;
        this.controlador = controlador;
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelTotal.setText("Total: ");
        jPanel1.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 350, -1));

        jButton1.setText("Cerrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatus.setText("status");
        jPanel1.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        controlador.ocultarPantallaStatusProducto();
        controlador.limpiarCarrito();
        controlador.limpiarStatusPago();
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        if(modeloLeible.obtenerStatusPago() != null){
            cargarDatos();
            this.setVisible(modeloLeible.isMostrandoPantallaStatusPago());
        }
    
        
    }
    
    private void cargarDatos() {
        entidades.StatusPago statusPago = modeloLeible.obtenerStatusPago();

        String estado = statusPago.getEstado().toString();

        if("SIN_STOCK".equals(estado) || "ERROR".equals(estado)) {
            jLabelStatus.setForeground(Color.red);
        } else {
            jLabelStatus.setForeground(Color.green);
        }

        jLabelStatus.setText(estado);
        jLabelTotal.setText("Total: " + statusPago.getTotal());
    }
}
