package vista;

import interfaces.Subscriber;
import javax.swing.text.AbstractDocument;
import utils.PrecioFilter;
import utils.SoloEnterosPositivosFilter;

/**
 *
 * @author janot
 */
public class AgregarProducto extends javax.swing.JDialog implements Subscriber{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarProducto.class.getName());

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelStock = new javax.swing.JLabel();
        jTextFieldStock = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelIdProducto = new javax.swing.JLabel();
        jTextFieldIdProducto = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(0, 153, 255));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelStock.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStock.setText("Stock:");
        jPanelPrincipal.add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 120, -1));
        jPanelPrincipal.add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 140, 30));
        ((AbstractDocument) jTextFieldStock.getDocument())
        .setDocumentFilter(new SoloEnterosPositivosFilter());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Agregar Producto");
        jPanelPrincipal.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabelIdProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdProducto.setText("Id Producto:");
        jPanelPrincipal.add(jLabelIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, -1));
        jPanelPrincipal.add(jTextFieldIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 140, 30));
        jPanelPrincipal.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, 30));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jPanelPrincipal.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, -1));

        jLabelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecio.setText("Precio:");
        jPanelPrincipal.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, -1));
        jPanelPrincipal.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, 30));
        ((AbstractDocument) jTextFieldPrecio.getDocument())
        .setDocumentFilter(new PrecioFilter());

        jButtonCancelar.setText("Cancelar");
        jPanelPrincipal.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, 30));

        jButtonAgregar.setText("Agregar");
        jPanelPrincipal.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 30));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelIdProducto;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField jTextFieldIdProducto;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
