package vista;

import entidades.Producto;
import entidades.StockProducto;
import interfaces.IControlador;
import interfaces.IModeloLeible;
import interfaces.Subscriber;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import utils.PrecioFilter;
import utils.SoloEnterosPositivosFilter;

/**
 *
 * @author janot
 */
public class AgregarProducto extends javax.swing.JDialog implements Subscriber{
    private IModeloLeible modeloLeible;
    private IControlador controlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarProducto.class.getName());

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto(java.awt.Frame parent, boolean modal, IModeloLeible modeloLeible, IControlador controlador) {
        super(parent, modal);
        this.modeloLeible = modeloLeible;
        this.controlador = controlador;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelStock = new javax.swing.JLabel();
        jTextFieldStock = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelIdProducto = new javax.swing.JLabel();
        jTextFieldIdProducto = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(0, 153, 255));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelStock.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStock.setText("Stock:");
        jPanelPrincipal.add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 120, -1));
        jPanelPrincipal.add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 140, 30));
        ((AbstractDocument) jTextFieldStock.getDocument())
        .setDocumentFilter(new SoloEnterosPositivosFilter());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Agregar Producto");
        jPanelPrincipal.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabelIdProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdProducto.setText("Id Producto:");
        jPanelPrincipal.add(jLabelIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, -1));
        jPanelPrincipal.add(jTextFieldIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 140, 30));
        jPanelPrincipal.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, 30));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jPanelPrincipal.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, -1));

        jLabelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecio.setText("Precio:");
        jPanelPrincipal.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, -1));
        jPanelPrincipal.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, 30));
        ((AbstractDocument) jTextFieldPrecio.getDocument())
        .setDocumentFilter(new PrecioFilter());

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, 30));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 30));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseClicked
        controlador.ocultarPantallaAgregarProducto();
        limpiarFormulario();
    }//GEN-LAST:event_jButtonCancelarMouseClicked

    private void jButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMouseClicked
        agregarProducto();
        limpiarFormulario();
    }//GEN-LAST:event_jButtonAgregarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelIdProducto;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField jTextFieldIdProducto;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        this.setVisible(modeloLeible.isMostrandoPantallaAgregarProducto());
    }
    
    private void agregarProducto(){

        boolean bandera = true;

        String idProducto = jTextFieldIdProducto.getText().trim();
        String nombreProducto = jTextFieldNombre.getText().trim();
        String precioTexto = jTextFieldPrecio.getText().trim();
        String stockTexto = jTextFieldStock.getText().trim();

        double precio = 0;
        int stock = 0;

        // Validar campos vacíos
        if(idProducto.isEmpty() || nombreProducto.isEmpty() 
                || precioTexto.isEmpty() || stockTexto.isEmpty()){

            JOptionPane.showMessageDialog(this,
                    "Todos los campos son obligatorios",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            bandera = false;
        }

        // Validar nombre
        if(nombreProducto.length() < 3){
            JOptionPane.showMessageDialog(this,
                    "El nombre debe tener al menos 3 caracteres",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            bandera = false;
        }

        // Validar precio
        try{
            precio = Double.parseDouble(precioTexto);
            if(precio <= 0){
                JOptionPane.showMessageDialog(this,
                        "El precio debe ser mayor a 0",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                bandera = false;
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "El precio debe ser un número válido",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            bandera = false;
        }

        // Validar stock
        try{
            stock = Integer.parseInt(stockTexto);
            if(stock < 0){
                JOptionPane.showMessageDialog(this,
                        "El stock no puede ser negativo",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                bandera = false;
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "El stock debe ser un número entero válido",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            bandera = false;
        }

        if(bandera){
            Producto producto = new Producto(idProducto, nombreProducto, precio);
            StockProducto stockProducto = new StockProducto(producto, stock);

            controlador.agregarProductoAInventario(stockProducto);
            controlador.ocultarPantallaAgregarProducto();
        }
    }
    
    private void limpiarFormulario(){
        jTextFieldIdProducto.setText("");
        jTextFieldNombre.setText("");
        jTextFieldPrecio.setText("0.00");
        jTextFieldStock.setText("0");
    }
}
