package vista;

import entidades.Producto;
import entidades.StockProducto;
import interfaces.IControlador;
import interfaces.IModeloLeible;
import interfaces.Subscriber;
import java.awt.Color;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author janot
 */
public class Inventario extends javax.swing.JFrame implements Subscriber{
    
    private final IModeloLeible modeloLeible;
    private final IControlador controlador;
    
    private DefaultTableModel modeloTabla;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inventario.class.getName());

    /**
     * Creates new form Inventario
     */
    public Inventario(IModeloLeible modeloLeible, IControlador controlador) {
        this.modeloLeible = modeloLeible;
        this.controlador = controlador;
        initComponents();
        inicializarTabla();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelNav = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanelBtnCerrarSesion = new javax.swing.JPanel();
        jLabelCerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(0, 153, 255));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNav.setBackground(new java.awt.Color(204, 102, 255));
        jPanelNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Agregar Producto");
        jPanelNav.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("INVENTARIO AMAZON");
        jPanelNav.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 2, 700, 90));

        jPanelPrincipal.add(jPanelNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));

        jTableProductos.setBackground(new java.awt.Color(51, 153, 255));
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(0).setResizable(false);
            jTableProductos.getColumnModel().getColumn(1).setResizable(false);
            jTableProductos.getColumnModel().getColumn(2).setResizable(false);
            jTableProductos.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 700, 280));

        jPanelBtnCerrarSesion.setBackground(new java.awt.Color(255, 51, 51));
        jPanelBtnCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrarSesion.setBackground(new java.awt.Color(204, 0, 51));
        jLabelCerrarSesion.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrarSesion.setText("Cerrar Sesion");
        jLabelCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseExited(evt);
            }
        });
        jPanelBtnCerrarSesion.add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 210, 40));

        jPanelPrincipal.add(jPanelBtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 210, 40));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseClicked
        controlador.ocultarPantallaInventario();
    }//GEN-LAST:event_jLabelCerrarSesionMouseClicked

    private void jLabelCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseEntered
        jPanelBtnCerrarSesion.setBackground(new Color(204,0,51));
    }//GEN-LAST:event_jLabelCerrarSesionMouseEntered

    private void jLabelCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseExited
        jPanelBtnCerrarSesion.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_jLabelCerrarSesionMouseExited

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBtnCerrarSesion;
    private javax.swing.JPanel jPanelNav;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        setVisible(modeloLeible.isMostrandoPantallaInventario());
        cargarInventario();
    }
    
    private void inicializarTabla() {

        String[] columnas = {"Id", "Nombre", "Precio", "Stock"};

        modeloTabla = new DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 2 -> Double.class;
                    case 3 -> Integer.class;
                    default -> String.class;
                };
            }
        };

        jTableProductos.setModel(modeloTabla);
    }
    
    private void cargarInventario() {
        List<StockProducto> listaInventario = modeloLeible.obtenerInventario();
        modeloTabla.setRowCount(0); // limpia tabla

        for (StockProducto sp : listaInventario) {

            Object[] fila = {
                sp.getProducto().getId(),
                sp.getProducto().getNombre(),
                sp.getProducto().getPrecio(),
                sp.getStock()
            };

            modeloTabla.addRow(fila);
        }
    } 
}
